# Generated by Django 4.1 on 2022-08-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catid',
            field=models.CharField(default='newcat', max_length=50),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='qid',
            field=models.CharField(default='newquiz', max_length=255, verbose_name='Quiz Id'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.questions'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.category'),
        ),
    ]
