# Generated by Django 4.1 on 2022-08-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_catid_quizzes_qid_alter_answers_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catid',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
    ]
